name: "Release MeTool App"

on:
  push:
    branches:
      - main # O workflow será ativado automaticamente a cada commit/push na branch main

jobs:
  release:
    permissions:
      contents: write # Permissão obrigatória para a Action criar a Release no GitHub
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'ubuntu-22.04'
            args: ''
          - platform: 'windows-latest'
            args: ''
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin'

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Baixar o código-fonte (Checkout)
        uses: actions/checkout@v4

      - name: Instalar dependências de sistema (Linux apenas)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências do Frontend
        run: npm install

      - name: Configurar o compilador Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Construir app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ${{ matrix.args }}
          
      - name: Buscar Versão do App
        id: version
        shell: bash
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Criar e Enviar para Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: 'Mevideo v${{ env.VERSION }}'
          body: |
            ## Build Automática do Mevideo
            
            **Patch Notes:**
            - Nova build gerada automaticamente para a versão `${{ env.VERSION }}`.
            - Commit: `${{ github.sha }}`
            
            > *Para instalar, faça o download do arquivo correspondente ao seu sistema operacional abaixo (`.exe` ou `.msi` para Windows, `.AppImage` ou `.deb` para Linux e `.dmg` para MacOS).*
          draft: false
          prerelease: true
          files: |
            src-tauri/target/release/bundle/deb/*.deb
            src-tauri/target/release/bundle/rpm/*.rpm
            src-tauri/target/release/bundle/appimage/*.AppImage
            src-tauri/target/release/bundle/msi/*.msi
            src-tauri/target/release/bundle/nsis/*.exe
            src-tauri/target/aarch64-apple-darwin/release/bundle/dmg/*.dmg
            src-tauri/target/aarch64-apple-darwin/release/bundle/macos/*.app.tar.gz
